networks:
  main-network:

services:
  message_broker:
    build: 
      context: ./rabbitmq_image
      dockerfile: Dockerfile
    container_name: demo-broker
    networks:
      - main-network
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:4.4.18
    networks:
      - main-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: image_records
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./bootstrap/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro


volumes:
  mongo-data: